services:
  pitsburg_backend:
    container_name: 'pitsburg_backend'
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "5000", "--workers", "4", "--reload"]
    ports:
      - "5000:5000"
    depends_on:
      - db
    restart: always
    volumes:
      - ./src:/app/src
      - ./alembic:/app/alembic

  db:
    container_name: 'pitsburg_db'
    image: pistburg_task-db
#    build:
#      context: ./postgres
#      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: pitsburg
      POSTGRES_USER: pits
      POSTGRES_PASSWD: burg
      POSTGRES_HOST: 5432
    ports:
      - "5429:5432"
    volumes:
      - postgresvolume:/var/lib/postgresql/data
    restart: always

volumes:
  postgresvolume:
    driver: local