services:
  pitsburg_backend:
    container_name: 'pitsburg_backend'
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["sh", "script.sh"]
    ports:
      - "5000:8000"
    depends_on:
      - db
    restart: always
    volumes:
      - ./src:/app/src
      - ./alembic/env.py:/app/alembic/env.py
      - ./script.sh:/app/script.sh

  db:
    container_name: 'pitsburg_db'
    image: pistburg_task-db
#    build:
#      context: ./postgres
#      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: pitsburg
      POSTGRES_USER: pits
      POSTGRES_PASSWD: burg
      POSTGRES_HOST: 5432
    ports:
      - "5429:5432"
    volumes:
      - postgresvolume:/var/lib/postgresql/data
    restart: always

volumes:
  postgresvolume:
    driver: local